import unittest
import os
from .buffer import ParserBuffer
from .file import ProtoFile

class TestProtoFile(unittest.TestCase):
    def test_basic_proto_file(self):
        buf = ParserBuffer('syntax = "proto3"; package foo; message Bar {}')
        result = ProtoFile.parse(buf)

        self.assertIsNotNone(result.syntax)
        self.assertIsNotNone(result.package)
        self.assertEqual(".foo", result.package.name.full)
        self.assertEqual(0, len(result.options))
        self.assertEqual(0, len(result.imports))
        self.assertEqual(0, len(result.enums))
        self.assertEqual(1, len(result.messages))
        self.assertEqual(0, len(result.services))

    def test_golden_proto3(self):
        # Get the directory of the current test file
        test_dir = os.path.dirname(os.path.abspath(__file__))
        proto3_path = os.path.join(test_dir, 'test', 'proto3.proto')

        with open(proto3_path, 'r') as f:
            file_content = f.read()

        buf = ParserBuffer(file_content)
        pf = ProtoFile.parse(buf)

        self.assertEqual("2023", pf.edition.edition)
        self.assertEqual(".protobuf_test_messages.editions.proto3", pf.package.name.full)

        self.assertEqual(6, len(pf.imports))
        self.assertEqual("protobuf/any.proto", pf.imports[0].path)
        self.assertEqual("protobuf/duration.proto", pf.imports[1].path)
        self.assertEqual("protobuf/field_mask.proto", pf.imports[2].path)
        self.assertEqual("protobuf/struct.proto", pf.imports[3].path)
        self.assertEqual("protobuf/timestamp.proto", pf.imports[4].path)
        self.assertEqual("protobuf/wrappers.proto", pf.imports[5].path)

        self.assertEqual(4, len(pf.options))
        self.assertEqual("features.field_presence", pf.options[0].name)
        self.assertEqual("IMPLICIT", pf.options[0].value)
        self.assertEqual("java_package", pf.options[1].name)
        self.assertEqual('"com.google.protobuf_test_messages.editions.proto3"', pf.options[1].value)
        self.assertEqual("objc_class_prefix", pf.options[2].name)
        self.assertEqual('"EditionsProto3"', pf.options[2].value)
        self.assertEqual("optimize_for", pf.options[3].name)
        self.assertEqual("SPEED", pf.options[3].value)

        self.assertEqual(1, len(pf.enums))
        self.assertEqual("ForeignEnum", pf.enums[0].name.name)
        self.assertEqual(3, len(pf.enums[0].fields))
        self.assertEqual("FOREIGN_FOO", pf.enums[0].fields[0].name)
        self.assertEqual(0, pf.enums[0].fields[0].index)
        self.assertEqual("FOREIGN_BAR", pf.enums[0].fields[1].name)
        self.assertEqual(1, pf.enums[0].fields[1].index)
        self.assertEqual("FOREIGN_BAZ", pf.enums[0].fields[2].name)
        self.assertEqual(2, pf.enums[0].fields[2].index)

        fm = pf.messages[1]
        self.assertEqual("ForeignMessage", fm.name.name)
        self.assertEqual(1, len(fm.fields))
        self.assertEqual("c", fm.fields[0].f_name)
        self.assertEqual("int32", fm.fields[0].f_type.src)
        self.assertTrue(fm.fields[0].f_type.is_scalar)
        self.assertEqual(1, fm.fields[0].index)

        nm = pf.messages[2]
        self.assertEqual("NullHypothesisProto3", nm.name.name)
        self.assertEqual(0, len(nm.fields))

        em = pf.messages[3]
        self.assertEqual("EnumOnlyProto3", em.name.name)
        self.assertEqual(1, len(em.enums))
        self.assertEqual(".protobuf_test_messages.editions.proto3.EnumOnlyProto3.Bool", em.enums[0].name.full)
        self.assertEqual(2, len(em.enums[0].fields))
        self.assertEqual("kFalse", em.enums[0].fields[0].name)
        self.assertEqual(0, em.enums[0].fields[0].index)
        self.assertEqual("kTrue", em.enums[0].fields[1].name)
        self.assertEqual(1, em.enums[0].fields[1].index)

        am = pf.messages[0]
        self.assertEqual("TestAllTypesProto3", am.name.name)

        nm2 = am.messages[0]
        self.assertEqual(".protobuf_test_messages.editions.proto3.TestAllTypesProto3.NestedMessage", nm2.name.full)
        self.assertEqual(2, len(nm2.fields))
        self.assertEqual("a", nm2.fields[0].f_name)
        self.assertEqual("int32", nm2.fields[0].f_type.src)
        self.assertTrue(nm2.fields[0].f_type.is_scalar)
        self.assertEqual(1, nm2.fields[0].index)
        self.assertEqual("corecursive", nm2.fields[1].f_name)
        self.assertEqual("TestAllTypesProto3", nm2.fields[1].f_type.src)
        self.assertFalse(nm2.fields[1].f_type.is_scalar)
        self.assertEqual(2, nm2.fields[1].index)

        ne = am.enums[0]
        self.assertEqual(".protobuf_test_messages.editions.proto3.TestAllTypesProto3.NestedEnum", ne.name.full)
        self.assertEqual(4, len(ne.fields))
        self.assertEqual("FOO", ne.fields[0].name)
        self.assertEqual(0, ne.fields[0].index)
        self.assertEqual("BAR", ne.fields[1].name)
        self.assertEqual(1, ne.fields[1].index)
        self.assertEqual("BAZ", ne.fields[2].name)
        self.assertEqual(2, ne.fields[2].index)
        self.assertEqual("NEG", ne.fields[3].name)
        self.assertEqual(-1, ne.fields[3].index)

        ae = am.enums[1]
        self.assertEqual(".protobuf_test_messages.editions.proto3.TestAllTypesProto3.AliasedEnum", ae.name.full)
        self.assertEqual(6, len(ae.fields))
        self.assertEqual("ALIAS_FOO", ae.fields[0].name)
        self.assertEqual(0, ae.fields[0].index)
        self.assertEqual("ALIAS_BAR", ae.fields[1].name)
        self.assertEqual(1, ae.fields[1].index)
        self.assertEqual("ALIAS_BAZ", ae.fields[2].name)
        self.assertEqual(2, ae.fields[2].index)
        self.assertEqual("MOO", ae.fields[3].name)
        self.assertEqual(2, ae.fields[3].index)
        self.assertEqual("moo", ae.fields[4].name)
        self.assertEqual(2, ae.fields[4].index)
        self.assertEqual("bAz", ae.fields[5].name)
        self.assertEqual(2, ae.fields[5].index)
        self.assertEqual(1, len(ae.options))
        self.assertEqual("allow_alias", ae.options[0].name)
        self.assertEqual("true", ae.options[0].value)

        self.assertEqual("optional_int32", am.fields[0].f_name)
        self.assertEqual("int32", am.fields[0].f_type.src)
        self.assertEqual(1, am.fields[0].index)
        self.assertEqual("optional_int64", am.fields[1].f_name)
        self.assertEqual("int64", am.fields[1].f_type.src)
        self.assertEqual(2, am.fields[1].index)
        self.assertEqual("optional_uint32", am.fields[2].f_name)
        self.assertEqual("uint32", am.fields[2].f_type.src)
        self.assertEqual(3, am.fields[2].index)
        self.assertEqual("optional_uint64", am.fields[3].f_name)
        self.assertEqual("uint64", am.fields[3].f_type.src)
        self.assertEqual(4, am.fields[3].index)
        self.assertEqual("optional_sint32", am.fields[4].f_name)
        self.assertEqual("sint32", am.fields[4].f_type.src)
        self.assertEqual(5, am.fields[4].index)
        self.assertEqual("optional_sint64", am.fields[5].f_name)
        self.assertEqual("sint64", am.fields[5].f_type.src)
        self.assertEqual(6, am.fields[5].index)
        self.assertEqual("optional_fixed32", am.fields[6].f_name)
        self.assertEqual("fixed32", am.fields[6].f_type.src)
        self.assertEqual(7, am.fields[6].index)
        self.assertEqual("optional_fixed64", am.fields[7].f_name)
        self.assertEqual("fixed64", am.fields[7].f_type.src)
        self.assertEqual(8, am.fields[7].index)
        self.assertEqual("optional_sfixed32", am.fields[8].f_name)
        self.assertEqual("sfixed32", am.fields[8].f_type.src)
        self.assertEqual(9, am.fields[8].index)
        self.assertEqual("optional_sfixed64", am.fields[9].f_name)
        self.assertEqual("sfixed64", am.fields[9].f_type.src)
        self.assertEqual(10, am.fields[9].index)
        self.assertEqual("optional_float", am.fields[10].f_name)
        self.assertEqual("float", am.fields[10].f_type.src)
        self.assertEqual(11, am.fields[10].index)
        self.assertEqual("optional_double", am.fields[11].f_name)
        self.assertEqual("double", am.fields[11].f_type.src)
        self.assertEqual(12, am.fields[11].index)
        self.assertEqual("optional_bool", am.fields[12].f_name)
        self.assertEqual("bool", am.fields[12].f_type.src)
        self.assertEqual(13, am.fields[12].index)
        self.assertEqual("optional_string", am.fields[13].f_name)
        self.assertEqual("string", am.fields[13].f_type.src)
        self.assertEqual(14, am.fields[13].index)
        self.assertEqual("optional_bytes", am.fields[14].f_name)
        self.assertEqual("bytes", am.fields[14].f_type.src)
        self.assertEqual(15, am.fields[14].index)
        self.assertEqual("optional_nested_message", am.fields[15].f_name)
        self.assertEqual("NestedMessage", am.fields[15].f_type.src)
        self.assertEqual(18, am.fields[15].index)
        self.assertEqual("optional_foreign_message", am.fields[16].f_name)
        self.assertEqual("ForeignMessage", am.fields[16].f_type.src)
        self.assertEqual(19, am.fields[16].index)
        self.assertEqual("optional_nested_enum", am.fields[17].f_name)
        self.assertEqual("NestedEnum", am.fields[17].f_type.src)
        self.assertEqual(21, am.fields[17].index)
        self.assertEqual("optional_foreign_enum", am.fields[18].f_name)
        self.assertEqual("ForeignEnum", am.fields[18].f_type.src)
        self.assertEqual(22, am.fields[18].index)
        self.assertEqual("optional_aliased_enum", am.fields[19].f_name)
        self.assertEqual("AliasedEnum", am.fields[19].f_type.src)
        self.assertEqual(23, am.fields[19].index)

        self.assertEqual("optional_string_piece", am.fields[20].f_name)
        self.assertEqual("string", am.fields[20].f_type.src)
        self.assertEqual(24, am.fields[20].index)
        self.assertEqual(1, len(am.fields[20].options))
        self.assertEqual("ctype", am.fields[20].options[0].name)
        self.assertEqual("STRING_PIECE", am.fields[20].options[0].value)

        self.assertEqual("optional_cord", am.fields[21].f_name)
        self.assertEqual("string", am.fields[21].f_type.src)
        self.assertEqual(25, am.fields[21].index)
        self.assertEqual(1, len(am.fields[21].options))
        self.assertEqual("ctype", am.fields[21].options[0].name)
        self.assertEqual("CORD", am.fields[21].options[0].value)

        self.assertEqual("recursive_message", am.fields[22].f_name)
        self.assertEqual("TestAllTypesProto3", am.fields[22].f_type.src)
        self.assertEqual(27, am.fields[22].index)

        self.assertEqual("repeated_int32", am.fields[23].f_name)
        self.assertEqual("int32", am.fields[23].f_type.src)
        self.assertEqual(31, am.fields[23].index)
        self.assertTrue(am.fields[23].repeated)

        self.assertEqual("repeated_int64", am.fields[24].f_name)
        self.assertEqual("int64", am.fields[24].f_type.src)
        self.assertEqual(32, am.fields[24].index)
        self.assertTrue(am.fields[24].repeated)

        self.assertEqual("repeated_uint32", am.fields[25].f_name)
        self.assertEqual("uint32", am.fields[25].f_type.src)
        self.assertEqual(33, am.fields[25].index)
        self.assertTrue(am.fields[25].repeated)

        self.assertEqual("repeated_uint64", am.fields[26].f_name)
        self.assertEqual("uint64", am.fields[26].f_type.src)
        self.assertEqual(34, am.fields[26].index)
        self.assertTrue(am.fields[26].repeated)

        self.assertEqual("repeated_sint32", am.fields[27].f_name)
        self.assertEqual("sint32", am.fields[27].f_type.src)
        self.assertEqual(35, am.fields[27].index)
        self.assertTrue(am.fields[27].repeated)

        self.assertEqual("repeated_sint64", am.fields[28].f_name)
        self.assertEqual("sint64", am.fields[28].f_type.src)
        self.assertEqual(36, am.fields[28].index)
        self.assertTrue(am.fields[28].repeated)

        self.assertEqual("repeated_fixed32", am.fields[29].f_name)
        self.assertEqual("fixed32", am.fields[29].f_type.src)
        self.assertEqual(37, am.fields[29].index)
        self.assertTrue(am.fields[29].repeated)

        self.assertEqual("repeated_fixed64", am.fields[30].f_name)
        self.assertEqual("fixed64", am.fields[30].f_type.src)
        self.assertEqual(38, am.fields[30].index)
        self.assertTrue(am.fields[30].repeated)

        self.assertEqual("repeated_sfixed32", am.fields[31].f_name)
        self.assertEqual("sfixed32", am.fields[31].f_type.src)
        self.assertEqual(39, am.fields[31].index)
        self.assertTrue(am.fields[31].repeated)

        self.assertEqual("repeated_sfixed64", am.fields[32].f_name)
        self.assertEqual("sfixed64", am.fields[32].f_type.src)
        self.assertEqual(40, am.fields[32].index)
        self.assertTrue(am.fields[32].repeated)

        self.assertEqual("repeated_float", am.fields[33].f_name)
        self.assertEqual("float", am.fields[33].f_type.src)
        self.assertEqual(41, am.fields[33].index)
        self.assertTrue(am.fields[33].repeated)

        self.assertEqual("repeated_double", am.fields[34].f_name)
        self.assertEqual("double", am.fields[34].f_type.src)
        self.assertEqual(42, am.fields[34].index)
        self.assertTrue(am.fields[34].repeated)

        self.assertEqual("repeated_bool", am.fields[35].f_name)
        self.assertEqual("bool", am.fields[35].f_type.src)
        self.assertEqual(43, am.fields[35].index)
        self.assertTrue(am.fields[35].repeated)

        self.assertEqual("repeated_string", am.fields[36].f_name)
        self.assertEqual("string", am.fields[36].f_type.src)
        self.assertEqual(44, am.fields[36].index)
        self.assertTrue(am.fields[36].repeated)

        self.assertEqual("repeated_bytes", am.fields[37].f_name)
        self.assertEqual("bytes", am.fields[37].f_type.src)
        self.assertEqual(45, am.fields[37].index)
        self.assertTrue(am.fields[37].repeated)

        self.assertEqual("repeated_nested_message", am.fields[38].f_name)
        self.assertEqual("NestedMessage", am.fields[38].f_type.src)
        self.assertEqual(48, am.fields[38].index)
        self.assertTrue(am.fields[38].repeated)

        self.assertEqual("repeated_foreign_message", am.fields[39].f_name)
        self.assertEqual("ForeignMessage", am.fields[39].f_type.src)
        self.assertEqual(49, am.fields[39].index)
        self.assertTrue(am.fields[39].repeated)

        self.assertEqual("repeated_nested_enum", am.fields[40].f_name)
        self.assertEqual("NestedEnum", am.fields[40].f_type.src)
        self.assertEqual(51, am.fields[40].index)
        self.assertTrue(am.fields[40].repeated)

        self.assertEqual("repeated_foreign_enum", am.fields[41].f_name)
        self.assertEqual("ForeignEnum", am.fields[41].f_type.src)
        self.assertEqual(52, am.fields[41].index)
        self.assertTrue(am.fields[41].repeated)

        self.assertEqual("repeated_string_piece", am.fields[42].f_name)
        self.assertEqual("string", am.fields[42].f_type.src)
        self.assertEqual(54, am.fields[42].index)
        self.assertTrue(am.fields[42].repeated)
        self.assertEqual(1, len(am.fields[42].options))
        self.assertEqual("ctype", am.fields[42].options[0].name)
        self.assertEqual("STRING_PIECE", am.fields[42].options[0].value)

        self.assertEqual("repeated_cord", am.fields[43].f_name)
        self.assertEqual("string", am.fields[43].f_type.src)
        self.assertEqual(55, am.fields[43].index)
        self.assertTrue(am.fields[43].repeated)
        self.assertEqual(1, len(am.fields[43].options))
        self.assertEqual("ctype", am.fields[43].options[0].name)
        self.assertEqual("CORD", am.fields[43].options[0].value)

        self.assertEqual("packed_int32", am.fields[44].f_name)
        self.assertEqual("int32", am.fields[44].f_type.src)
        self.assertEqual(75, am.fields[44].index)
        self.assertTrue(am.fields[44].repeated)

        self.assertEqual("packed_int64", am.fields[45].f_name)
        self.assertEqual("int64", am.fields[45].f_type.src)
        self.assertEqual(76, am.fields[45].index)
        self.assertTrue(am.fields[45].repeated)

        self.assertEqual("packed_uint32", am.fields[46].f_name)
        self.assertEqual("uint32", am.fields[46].f_type.src)
        self.assertEqual(77, am.fields[46].index)
        self.assertTrue(am.fields[46].repeated)

        self.assertEqual("packed_uint64", am.fields[47].f_name)
        self.assertEqual("uint64", am.fields[47].f_type.src)
        self.assertEqual(78, am.fields[47].index)
        self.assertTrue(am.fields[47].repeated)

        self.assertEqual("packed_sint32", am.fields[48].f_name)
        self.assertEqual("sint32", am.fields[48].f_type.src)
        self.assertEqual(79, am.fields[48].index)
        self.assertTrue(am.fields[48].repeated)

        self.assertEqual("packed_sint64", am.fields[49].f_name)
        self.assertEqual("sint64", am.fields[49].f_type.src)
        self.assertEqual(80, am.fields[49].index)
        self.assertTrue(am.fields[49].repeated)

        self.assertEqual("packed_fixed32", am.fields[50].f_name)
        self.assertEqual("fixed32", am.fields[50].f_type.src)
        self.assertEqual(81, am.fields[50].index)
        self.assertTrue(am.fields[50].repeated)

        self.assertEqual("packed_fixed64", am.fields[51].f_name)
        self.assertEqual("fixed64", am.fields[51].f_type.src)
        self.assertEqual(82, am.fields[51].index)
        self.assertTrue(am.fields[51].repeated)

        self.assertEqual("packed_sfixed32", am.fields[52].f_name)
        self.assertEqual("sfixed32", am.fields[52].f_type.src)
        self.assertEqual(83, am.fields[52].index)
        self.assertTrue(am.fields[52].repeated)

        self.assertEqual("packed_sfixed64", am.fields[53].f_name)
        self.assertEqual("sfixed64", am.fields[53].f_type.src)
        self.assertEqual(84, am.fields[53].index)
        self.assertTrue(am.fields[53].repeated)

        self.assertEqual("packed_float", am.fields[54].f_name)
        self.assertEqual("float", am.fields[54].f_type.src)
        self.assertEqual(85, am.fields[54].index)
        self.assertTrue(am.fields[54].repeated)

        self.assertEqual("packed_double", am.fields[55].f_name)
        self.assertEqual("double", am.fields[55].f_type.src)
        self.assertEqual(86, am.fields[55].index)
        self.assertTrue(am.fields[55].repeated)

        self.assertEqual("packed_bool", am.fields[56].f_name)
        self.assertEqual("bool", am.fields[56].f_type.src)
        self.assertEqual(87, am.fields[56].index)
        self.assertTrue(am.fields[56].repeated)

        self.assertEqual("packed_nested_enum", am.fields[57].f_name)
        self.assertEqual("NestedEnum", am.fields[57].f_type.src)
        self.assertEqual(88, am.fields[57].index)
        self.assertTrue(am.fields[57].repeated)

        self.assertEqual("unpacked_int32", am.fields[58].f_name)
        self.assertEqual("int32", am.fields[58].f_type.src)
        self.assertEqual(89, am.fields[58].index)
        self.assertTrue(am.fields[58].repeated)
        self.assertEqual(1, len(am.fields[58].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[58].options[0].name)
        self.assertEqual("EXPANDED", am.fields[58].options[0].value)

        self.assertEqual("unpacked_int64", am.fields[59].f_name)
        self.assertEqual("int64", am.fields[59].f_type.src)
        self.assertEqual(90, am.fields[59].index)
        self.assertTrue(am.fields[59].repeated)
        self.assertEqual(1, len(am.fields[59].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[59].options[0].name)
        self.assertEqual("EXPANDED", am.fields[59].options[0].value)

        self.assertEqual("unpacked_uint32", am.fields[60].f_name)
        self.assertEqual("uint32", am.fields[60].f_type.src)
        self.assertEqual(91, am.fields[60].index)
        self.assertTrue(am.fields[60].repeated)
        self.assertEqual(1, len(am.fields[60].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[60].options[0].name)
        self.assertEqual("EXPANDED", am.fields[60].options[0].value)

        self.assertEqual("unpacked_uint64", am.fields[61].f_name)
        self.assertEqual("uint64", am.fields[61].f_type.src)
        self.assertEqual(92, am.fields[61].index)
        self.assertTrue(am.fields[61].repeated)
        self.assertEqual(1, len(am.fields[61].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[61].options[0].name)
        self.assertEqual("EXPANDED", am.fields[61].options[0].value)

        self.assertEqual("unpacked_sint32", am.fields[62].f_name)
        self.assertEqual("sint32", am.fields[62].f_type.src)
        self.assertEqual(93, am.fields[62].index)
        self.assertTrue(am.fields[62].repeated)
        self.assertEqual(1, len(am.fields[62].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[62].options[0].name)
        self.assertEqual("EXPANDED", am.fields[62].options[0].value)

        self.assertEqual("unpacked_sint64", am.fields[63].f_name)
        self.assertEqual("sint64", am.fields[63].f_type.src)
        self.assertEqual(94, am.fields[63].index)
        self.assertTrue(am.fields[63].repeated)
        self.assertEqual(1, len(am.fields[63].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[63].options[0].name)
        self.assertEqual("EXPANDED", am.fields[63].options[0].value)

        self.assertEqual("unpacked_fixed32", am.fields[64].f_name)
        self.assertEqual("fixed32", am.fields[64].f_type.src)
        self.assertEqual(95, am.fields[64].index)
        self.assertTrue(am.fields[64].repeated)
        self.assertEqual(1, len(am.fields[64].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[64].options[0].name)
        self.assertEqual("EXPANDED", am.fields[64].options[0].value)

        self.assertEqual("unpacked_fixed64", am.fields[65].f_name)
        self.assertEqual("fixed64", am.fields[65].f_type.src)
        self.assertEqual(96, am.fields[65].index)
        self.assertTrue(am.fields[65].repeated)
        self.assertEqual(1, len(am.fields[65].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[65].options[0].name)
        self.assertEqual("EXPANDED", am.fields[65].options[0].value)

        self.assertEqual("unpacked_sfixed32", am.fields[66].f_name)
        self.assertEqual("sfixed32", am.fields[66].f_type.src)
        self.assertEqual(97, am.fields[66].index)
        self.assertTrue(am.fields[66].repeated)
        self.assertEqual(1, len(am.fields[66].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[66].options[0].name)
        self.assertEqual("EXPANDED", am.fields[66].options[0].value)

        self.assertEqual("unpacked_sfixed64", am.fields[67].f_name)
        self.assertEqual("sfixed64", am.fields[67].f_type.src)
        self.assertEqual(98, am.fields[67].index)
        self.assertTrue(am.fields[67].repeated)
        self.assertEqual(1, len(am.fields[67].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[67].options[0].name)
        self.assertEqual("EXPANDED", am.fields[67].options[0].value)

        self.assertEqual("unpacked_float", am.fields[68].f_name)
        self.assertEqual("float", am.fields[68].f_type.src)
        self.assertEqual(99, am.fields[68].index)
        self.assertTrue(am.fields[68].repeated)
        self.assertEqual(1, len(am.fields[68].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[68].options[0].name)
        self.assertEqual("EXPANDED", am.fields[68].options[0].value)

        self.assertEqual("unpacked_double", am.fields[69].f_name)
        self.assertEqual("double", am.fields[69].f_type.src)
        self.assertEqual(100, am.fields[69].index)
        self.assertTrue(am.fields[69].repeated)
        self.assertEqual(1, len(am.fields[69].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[69].options[0].name)
        self.assertEqual("EXPANDED", am.fields[69].options[0].value)

        self.assertEqual("unpacked_bool", am.fields[70].f_name)
        self.assertEqual("bool", am.fields[70].f_type.src)
        self.assertEqual(101, am.fields[70].index)
        self.assertTrue(am.fields[70].repeated)
        self.assertEqual(1, len(am.fields[70].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[70].options[0].name)
        self.assertEqual("EXPANDED", am.fields[70].options[0].value)

        self.assertEqual("unpacked_nested_enum", am.fields[71].f_name)
        self.assertEqual("NestedEnum", am.fields[71].f_type.src)
        self.assertEqual(102, am.fields[71].index)
        self.assertTrue(am.fields[71].repeated)
        self.assertEqual(1, len(am.fields[71].options))
        self.assertEqual("features.repeated_field_encoding", am.fields[71].options[0].name)
        self.assertEqual("EXPANDED", am.fields[71].options[0].value)

        self.assertEqual("map_int32_int32", am.maps[0].f_name)
        self.assertEqual("int32", am.maps[0].key_type)
        self.assertEqual("int32", am.maps[0].value_type.src)
        self.assertEqual(56, am.maps[0].index)

        self.assertEqual("map_int64_int64", am.maps[1].f_name)
        self.assertEqual("int64", am.maps[1].key_type)
        self.assertEqual("int64", am.maps[1].value_type.src)
        self.assertEqual(57, am.maps[1].index)

        self.assertEqual("map_uint32_uint32", am.maps[2].f_name)
        self.assertEqual("uint32", am.maps[2].key_type)
        self.assertEqual("uint32", am.maps[2].value_type.src)
        self.assertEqual(58, am.maps[2].index)

        self.assertEqual("map_uint64_uint64", am.maps[3].f_name)
        self.assertEqual("uint64", am.maps[3].key_type)
        self.assertEqual("uint64", am.maps[3].value_type.src)
        self.assertEqual(59, am.maps[3].index)

        self.assertEqual("map_sint32_sint32", am.maps[4].f_name)
        self.assertEqual("sint32", am.maps[4].key_type)
        self.assertEqual("sint32", am.maps[4].value_type.src)
        self.assertEqual(60, am.maps[4].index)

        self.assertEqual("map_sint64_sint64", am.maps[5].f_name)
        self.assertEqual("sint64", am.maps[5].key_type)
        self.assertEqual("sint64", am.maps[5].value_type.src)
        self.assertEqual(61, am.maps[5].index)

        self.assertEqual("map_fixed32_fixed32", am.maps[6].f_name)
        self.assertEqual("fixed32", am.maps[6].key_type)
        self.assertEqual("fixed32", am.maps[6].value_type.src)
        self.assertEqual(62, am.maps[6].index)

        self.assertEqual("map_fixed64_fixed64", am.maps[7].f_name)
        self.assertEqual("fixed64", am.maps[7].key_type)
        self.assertEqual("fixed64", am.maps[7].value_type.src)
        self.assertEqual(63, am.maps[7].index)

        self.assertEqual("map_sfixed32_sfixed32", am.maps[8].f_name)
        self.assertEqual("sfixed32", am.maps[8].key_type)
        self.assertEqual("sfixed32", am.maps[8].value_type.src)
        self.assertEqual(64, am.maps[8].index)

        self.assertEqual("map_sfixed64_sfixed64", am.maps[9].f_name)
        self.assertEqual("sfixed64", am.maps[9].key_type)
        self.assertEqual("sfixed64", am.maps[9].value_type.src)
        self.assertEqual(65, am.maps[9].index)

        self.assertEqual("map_int32_float", am.maps[10].f_name)
        self.assertEqual("int32", am.maps[10].key_type)
        self.assertEqual("float", am.maps[10].value_type.src)
        self.assertEqual(66, am.maps[10].index)

        self.assertEqual("map_int32_double", am.maps[11].f_name)
        self.assertEqual("int32", am.maps[11].key_type)
        self.assertEqual("double", am.maps[11].value_type.src)
        self.assertEqual(67, am.maps[11].index)

        self.assertEqual("map_bool_bool", am.maps[12].f_name)
        self.assertEqual("bool", am.maps[12].key_type)
        self.assertEqual("bool", am.maps[12].value_type.src)
        self.assertEqual(68, am.maps[12].index)

        self.assertEqual("map_string_string", am.maps[13].f_name)
        self.assertEqual("string", am.maps[13].key_type)
        self.assertEqual("string", am.maps[13].value_type.src)
        self.assertEqual(69, am.maps[13].index)

        self.assertEqual("map_string_bytes", am.maps[14].f_name)
        self.assertEqual("string", am.maps[14].key_type)
        self.assertEqual("bytes", am.maps[14].value_type.src)
        self.assertEqual(70, am.maps[14].index)

        self.assertEqual("map_string_nested_message", am.maps[15].f_name)
        self.assertEqual("string", am.maps[15].key_type)
        self.assertEqual("NestedMessage", am.maps[15].value_type.src)
        self.assertEqual(71, am.maps[15].index)

        self.assertEqual("map_string_foreign_message", am.maps[16].f_name)
        self.assertEqual("string", am.maps[16].key_type)
        self.assertEqual("ForeignMessage", am.maps[16].value_type.src)
        self.assertEqual(72, am.maps[16].index)

        self.assertEqual("map_string_nested_enum", am.maps[17].f_name)
        self.assertEqual("string", am.maps[17].key_type)
        self.assertEqual("NestedEnum", am.maps[17].value_type.src)
        self.assertEqual(73, am.maps[17].index)

        self.assertEqual("map_string_foreign_enum", am.maps[18].f_name)
        self.assertEqual("string", am.maps[18].key_type)
        self.assertEqual("ForeignEnum", am.maps[18].value_type.src)
        self.assertEqual(74, am.maps[18].index)

        self.assertEqual("oneof_field", am.oneofs[0].name)
        self.assertEqual(111, am.oneofs[0].fields[0].index)
        self.assertEqual("oneof_uint32", am.oneofs[0].fields[0].f_name)
        self.assertEqual("uint32", am.oneofs[0].fields[0].f_type.src)
        self.assertEqual(112, am.oneofs[0].fields[1].index)
        self.assertEqual("oneof_nested_message", am.oneofs[0].fields[1].f_name)
        self.assertEqual("NestedMessage", am.oneofs[0].fields[1].f_type.src)
        self.assertEqual(113, am.oneofs[0].fields[2].index)
        self.assertEqual("oneof_string", am.oneofs[0].fields[2].f_name)
        self.assertEqual("string", am.oneofs[0].fields[2].f_type.src)
        self.assertEqual(114, am.oneofs[0].fields[3].index)
        self.assertEqual("oneof_bytes", am.oneofs[0].fields[3].f_name)
        self.assertEqual("bytes", am.oneofs[0].fields[3].f_type.src)
        self.assertEqual(115, am.oneofs[0].fields[4].index)
        self.assertEqual("oneof_bool", am.oneofs[0].fields[4].f_name)
        self.assertEqual("bool", am.oneofs[0].fields[4].f_type.src)
        self.assertEqual(116, am.oneofs[0].fields[5].index)
        self.assertEqual("oneof_uint64", am.oneofs[0].fields[5].f_name)
        self.assertEqual("uint64", am.oneofs[0].fields[5].f_type.src)
        self.assertEqual(117, am.oneofs[0].fields[6].index)
        self.assertEqual("oneof_float", am.oneofs[0].fields[6].f_name)
        self.assertEqual("float", am.oneofs[0].fields[6].f_type.src)
        self.assertEqual(118, am.oneofs[0].fields[7].index)
        self.assertEqual("oneof_double", am.oneofs[0].fields[7].f_name)
        self.assertEqual("double", am.oneofs[0].fields[7].f_type.src)
        self.assertEqual(119, am.oneofs[0].fields[8].index)
        self.assertEqual("oneof_enum", am.oneofs[0].fields[8].f_name)
        self.assertEqual("NestedEnum", am.oneofs[0].fields[8].f_type.src)
        self.assertEqual(120, am.oneofs[0].fields[9].index)
        self.assertEqual("oneof_null_value", am.oneofs[0].fields[9].f_name)
        self.assertEqual("google.protobuf.NullValue", am.oneofs[0].fields[9].f_type.src)

        self.assertEqual("501 to 510", am.reserved[0].items[0])

if __name__ == '__main__':
    unittest.main()