// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RxEnvelope {
    #[prost(uint64, tag = "1")]
    pub monotonic_stamp_ns: u64,
    #[prost(uint64, tag = "2")]
    pub local_stamp_ns: u64,
    #[prost(uint64, tag = "3")]
    pub app_start_id: u64,
    #[prost(enumeration = "VescTrampaSignalType", tag = "10")]
    pub signal_type: i32,
    #[prost(message, optional, tag = "11")]
    pub board: ::core::option::Option<VescTrampaBoard>,
    #[prost(message, optional, tag = "20")]
    pub board_packet: ::core::option::Option<VescTrampaBoardPacket>,
    #[prost(message, optional, tag = "30")]
    pub command: ::core::option::Option<TxEnvelope>,
    #[prost(string, tag = "50")]
    pub error: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxEnvelope {
    #[prost(uint64, tag = "1")]
    pub monotonic_stamp_ns: u64,
    #[prost(uint64, tag = "2")]
    pub local_stamp_ns: u64,
    #[prost(uint64, tag = "5")]
    pub app_start_id: u64,
    #[prost(bytes = "bytes", tag = "3")]
    pub target_board_uuid: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "4")]
    pub command_id: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "10")]
    pub board_command: ::core::option::Option<VescTrampaBoardCommand>,
    #[prost(message, optional, tag = "11")]
    pub motor_mode: ::core::option::Option<VescTrampaMotorModeCommand>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Command {
    #[prost(bytes = "bytes", tag = "1")]
    pub target_board_uuid: ::prost::bytes::Bytes,
    #[prost(message, optional, tag = "10")]
    pub board_command: ::core::option::Option<VescTrampaBoardCommand>,
    #[prost(message, optional, tag = "11")]
    pub motor_mode: ::core::option::Option<VescTrampaMotorModeCommand>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VescTrampaBoardCommand {
    #[prost(bytes = "bytes", tag = "1")]
    pub payload: ::prost::bytes::Bytes,
    #[prost(bool, tag = "2")]
    pub response_expected: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VescTrampaMotorModeCommand {
    #[prost(enumeration = "VescTrampaMotorMode", tag = "1")]
    pub mode: i32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VescTrampaBoardPacket {
    #[prost(uint32, tag = "1")]
    pub start_byte: u32,
    #[prost(uint32, tag = "2")]
    pub payload_len: u32,
    #[prost(uint32, tag = "3")]
    pub command_id: u32,
    #[prost(bytes = "bytes", tag = "4")]
    pub payload: ::prost::bytes::Bytes,
    #[prost(uint32, tag = "5")]
    pub crc: u32,
    #[prost(uint32, tag = "6")]
    pub end_byte: u32,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InferenceState {
    #[prost(bytes = "bytes", tag = "1")]
    pub last_inference_queue_ptr: ::prost::bytes::Bytes,
    #[prost(message, repeated, tag = "10")]
    pub boards: ::prost::alloc::vec::Vec<inference_state::BoardState>,
}
/// Nested message and enum types in `InferenceState`.
pub mod inference_state {
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct BoardState {
        #[prost(message, optional, tag = "1")]
        pub board: ::core::option::Option<super::VescTrampaBoard>,
        #[prost(enumeration = "super::VescTrampaMotorMode", tag = "2")]
        pub motor_mode: i32,
        #[prost(uint64, tag = "3")]
        pub monotonic_stamp_ns: u64,
        #[prost(uint64, tag = "4")]
        pub local_stamp_ns: u64,
        #[prost(uint64, tag = "5")]
        pub app_start_id: u64,
        #[prost(bytes = "bytes", tag = "10")]
        pub values_payload: ::prost::bytes::Bytes,
        #[prost(bytes = "bytes", tag = "11")]
        pub values_rx_pointer: ::prost::bytes::Bytes,
        #[prost(uint64, tag = "12")]
        pub values_monotonic_stamp_ns: u64,
        #[prost(uint64, tag = "13")]
        pub values_local_stamp_ns: u64,
        #[prost(uint64, tag = "14")]
        pub values_app_start_id: u64,
    }
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VescTrampaBoard {
    #[prost(string, tag = "1")]
    pub port_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub vid: u32,
    #[prost(uint32, tag = "3")]
    pub pid: u32,
    #[prost(string, tag = "4")]
    pub serial_number: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub manufacturer: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub product: ::prost::alloc::string::String,
    #[prost(uint32, tag = "7")]
    pub port_baud_rate: u32,
    #[prost(uint32, tag = "20")]
    pub firmware_major: u32,
    #[prost(uint32, tag = "21")]
    pub firmware_minor: u32,
    #[prost(string, tag = "22")]
    pub hardware_name: ::prost::alloc::string::String,
    #[prost(bytes = "bytes", tag = "23")]
    pub uuid: ::prost::bytes::Bytes,
    #[prost(bool, tag = "24")]
    pub pairing_done: bool,
    #[prost(uint32, tag = "25")]
    pub test_version_number: u32,
    #[prost(uint32, tag = "26")]
    pub hardware_type: u32,
    #[prost(uint32, tag = "27")]
    pub custom_config_count: u32,
    #[prost(bool, tag = "28")]
    pub has_phase_filters: bool,
    #[prost(uint32, tag = "29")]
    pub qml_hw: u32,
    #[prost(uint32, tag = "30")]
    pub qml_app: u32,
    #[prost(uint32, tag = "31")]
    pub nrf_flags: u32,
    #[prost(string, tag = "32")]
    pub firmware_name: ::prost::alloc::string::String,
    #[prost(uint32, tag = "33")]
    pub hardware_config_crc: u32,
    #[prost(bytes = "bytes", tag = "34")]
    pub firmware_info_extra_bytes: ::prost::bytes::Bytes,
    #[prost(bytes = "bytes", tag = "35")]
    pub firmware_info_raw_payload: ::prost::bytes::Bytes,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VescTrampaSignalType {
    Unspecified = 0,
    VescTrampaBoardConnect = 1,
    VescTrampaBoardDisconnect = 2,
    VescTrampaBoardPacket = 3,
    VescTrampaCommand = 4,
    VescTrampaCommandSuccess = 5,
    VescTrampaCommandRejected = 6,
    VescTrampaCommandFailed = 7,
}
impl VescTrampaSignalType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            VescTrampaSignalType::Unspecified => "VESC_TRAMPA_SIGNAL_TYPE_UNSPECIFIED",
            VescTrampaSignalType::VescTrampaBoardConnect => "VESC_TRAMPA_BOARD_CONNECT",
            VescTrampaSignalType::VescTrampaBoardDisconnect => {
                "VESC_TRAMPA_BOARD_DISCONNECT"
            }
            VescTrampaSignalType::VescTrampaBoardPacket => "VESC_TRAMPA_BOARD_PACKET",
            VescTrampaSignalType::VescTrampaCommand => "VESC_TRAMPA_COMMAND",
            VescTrampaSignalType::VescTrampaCommandSuccess => {
                "VESC_TRAMPA_COMMAND_SUCCESS"
            }
            VescTrampaSignalType::VescTrampaCommandRejected => {
                "VESC_TRAMPA_COMMAND_REJECTED"
            }
            VescTrampaSignalType::VescTrampaCommandFailed => "VESC_TRAMPA_COMMAND_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VESC_TRAMPA_SIGNAL_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "VESC_TRAMPA_BOARD_CONNECT" => Some(Self::VescTrampaBoardConnect),
            "VESC_TRAMPA_BOARD_DISCONNECT" => Some(Self::VescTrampaBoardDisconnect),
            "VESC_TRAMPA_BOARD_PACKET" => Some(Self::VescTrampaBoardPacket),
            "VESC_TRAMPA_COMMAND" => Some(Self::VescTrampaCommand),
            "VESC_TRAMPA_COMMAND_SUCCESS" => Some(Self::VescTrampaCommandSuccess),
            "VESC_TRAMPA_COMMAND_REJECTED" => Some(Self::VescTrampaCommandRejected),
            "VESC_TRAMPA_COMMAND_FAILED" => Some(Self::VescTrampaCommandFailed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum VescTrampaMotorMode {
    Unspecified = 0,
    Hold = 1,
}
impl VescTrampaMotorMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            VescTrampaMotorMode::Unspecified => "VESC_TRAMPA_MOTOR_MODE_UNSPECIFIED",
            VescTrampaMotorMode::Hold => "VESC_TRAMPA_MOTOR_MODE_HOLD",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VESC_TRAMPA_MOTOR_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "VESC_TRAMPA_MOTOR_MODE_HOLD" => Some(Self::Hold),
            _ => None,
        }
    }
}
